CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260805214117_InitialCreate') THEN
    CREATE TABLE customers (
        id uuid NOT NULL,
        name character varying(200) NOT NULL,
        email character varying(150) NOT NULL,
        rnc character varying(20) NOT NULL,
        created_at timestamp with time zone NOT NULL,
        created_by character varying(100),
        updated_at timestamp with time zone,
        updated_by character varying(100),
        deleted_at timestamp with time zone,
        deleted_by character varying(100),
        is_deleted boolean NOT NULL,
        CONSTRAINT pk_customers PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260805214117_InitialCreate') THEN
    CREATE TABLE ecf_documents (
        id uuid NOT NULL,
        ncf character varying(20),
        e_ncf character varying(20) NOT NULL,
        rnc_emisor character varying(20) NOT NULL,
        rnc_comprador character varying(20),
        tenant_id character varying(100) NOT NULL,
        source_txn_id character varying(100) NOT NULL,
        edit_sequence character varying(50) NOT NULL,
        document_kind character varying(50) NOT NULL,
        track_id character varying(100),
        state character varying(50) NOT NULL,
        total_amount numeric(18,2) NOT NULL,
        itbis_amount numeric(18,2) NOT NULL,
        security_code character varying(100),
        xml_content text NOT NULL,
        signed_xml_content text,
        dgii_response_xml text,
        receipt_date timestamp with time zone,
        created_at timestamp with time zone NOT NULL,
        created_by character varying(100),
        updated_at timestamp with time zone,
        updated_by character varying(100),
        deleted_at timestamp with time zone,
        deleted_by character varying(100),
        is_deleted boolean NOT NULL,
        CONSTRAINT pk_ecf_documents PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260805214117_InitialCreate') THEN
    CREATE TABLE ecf_idempotency_records (
        key text NOT NULL,
        created_by_worker_key_id text NOT NULL,
        payload_hash text NOT NULL,
        status integer NOT NULL,
        status_code integer NOT NULL,
        content_type text NOT NULL,
        response_body text NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone,
        expires_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ecf_idempotency_records" PRIMARY KEY (key)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260805214117_InitialCreate') THEN
    CREATE TABLE ecf_sequences (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        tenant_id text NOT NULL,
        tipo_comprobante text NOT NULL,
        prefix text NOT NULL,
        rango_desde bigint NOT NULL,
        rango_hasta bigint NOT NULL,
        secuencia_actual bigint NOT NULL,
        fecha_vencimiento timestamp with time zone,
        is_active boolean NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ecf_sequences" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260805214117_InitialCreate') THEN
    CREATE TABLE users (
        id uuid NOT NULL,
        username character varying(100) NOT NULL,
        email character varying(150) NOT NULL,
        password_hash text NOT NULL,
        role character varying(50) NOT NULL,
        created_at timestamp with time zone NOT NULL,
        created_by character varying(100),
        updated_at timestamp with time zone,
        updated_by character varying(100),
        deleted_at timestamp with time zone,
        deleted_by character varying(100),
        is_deleted boolean NOT NULL,
        CONSTRAINT pk_users PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260805214117_InitialCreate') THEN
    INSERT INTO customers (id, created_at, created_by, deleted_at, deleted_by, email, is_deleted, name, rnc, updated_at, updated_by)
    VALUES ('f98f6d61-d24f-4a0b-967b-1d7c0f135b5a', TIMESTAMPTZ '2026-06-26T00:00:00Z', 'System', NULL, NULL, 'consumidorfinal@ecfdgii.client.com', FALSE, 'Consumidor Final Genérico', '22400013743', NULL, NULL);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260805214117_InitialCreate') THEN
    INSERT INTO users (id, created_at, created_by, deleted_at, deleted_by, email, is_deleted, password_hash, role, updated_at, updated_by, username)
    VALUES ('9f3c7e09-e85d-452f-9877-c93d90fcb32d', TIMESTAMPTZ '2026-06-26T00:00:00Z', 'System', NULL, NULL, 'admin@ecfdgii.client.com', FALSE, '$2a$11$yHgpsPOsooH4yxAXvMiRXO.mA22AwAaRY.eb69RmF3v1JZBmu3T56', 'Admin', NULL, NULL, 'admin');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260805214117_InitialCreate') THEN
    CREATE INDEX ix_customers_rnc ON customers (rnc);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260805214117_InitialCreate') THEN
    CREATE INDEX ix_ecf_documents_state ON ecf_documents (state);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260805214117_InitialCreate') THEN
    CREATE INDEX ix_ecf_documents_track_id ON ecf_documents (track_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260805214117_InitialCreate') THEN
    CREATE UNIQUE INDEX uq_ecf_documents_rnc_emisor_encf ON ecf_documents (rnc_emisor, e_ncf);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260805214117_InitialCreate') THEN
    CREATE UNIQUE INDEX uq_ecf_documents_tenant_source_txn ON ecf_documents (tenant_id, source_txn_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260805214117_InitialCreate') THEN
    CREATE INDEX ix_ecf_idempotency_records_expires_at ON ecf_idempotency_records (expires_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260805214117_InitialCreate') THEN
    CREATE UNIQUE INDEX uq_ecf_sequences_tenant_tipo ON ecf_sequences (tenant_id, tipo_comprobante);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260805214117_InitialCreate') THEN
    CREATE UNIQUE INDEX uq_users_email ON users (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260805214117_InitialCreate') THEN
    CREATE UNIQUE INDEX uq_users_username ON users (username);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260805214117_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260805214117_InitialCreate', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806123843_RotateSeededAdminPasswordHash') THEN
    UPDATE users SET password_hash = '$2a$11$TrZocoksYo3ZzpTKy5XdZuw6LBumk7obuD5Viyzo/dTsdAA3ikkDW'
    WHERE id = '9f3c7e09-e85d-452f-9877-c93d90fcb32d';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806123843_RotateSeededAdminPasswordHash') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260806123843_RotateSeededAdminPasswordHash', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806141616_AddEcfStatusPollingColumns') THEN
    ALTER TABLE ecf_documents ADD last_status_check_at timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806141616_AddEcfStatusPollingColumns') THEN
    ALTER TABLE ecf_documents ADD sent_to_dgii_at timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806141616_AddEcfStatusPollingColumns') THEN
    ALTER TABLE ecf_documents ADD status_check_attempts integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806141616_AddEcfStatusPollingColumns') THEN
    CREATE INDEX ix_ecf_documents_state_last_status_check_at ON ecf_documents (state, last_status_check_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806141616_AddEcfStatusPollingColumns') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260806141616_AddEcfStatusPollingColumns', '10.0.10');
    END IF;
END $EF$;
COMMIT;

